#!/usr/bin/perl

use Crypt::OpenSSL::RSA;
use MIME::Base64;
use File::Slurp;

my $apikey = read_file('tmp/api_key');
my $pubkey = read_file('tmp/obf_public_key');

my $key = Crypt::OpenSSL::RSA->new_public_key($pubkey);
$key->use_pkcs1_padding;
my $decrypted = $key->public_decrypt( decode_base64($apikey) );
print $decrypted;
